### PR TITLE
add .po file

### PR DESCRIPTION
**Pull request by ngkiencuong**

### CODE REVIEW

**Comment by euroblaze** [comment]
Please provide instructions to translator for adding new stings, like a "howto".

**Comment by euroblaze** [comment]
@ngkiencuong 
Add these to the readme.md, now and in future, so translators always know, even if they change from module to module.

**Comment by euroblaze** [comment]
@simplify-m97 @ngkiencuong

The po file is empty.
https://github.com/euroblaze/partner_accounts/pull/5/files 
So translations are not possible.
Please add lang strings.

**Comment by euroblaze** [comment]
@ngkiencuong in future for po files, please ensure to obtain and add english strings, so translator can save it with German strings.

**Comment by ngkiencuong** [comment]
> @ngkiencuong in future for po files, please ensure to obtain and add english strings, so translator can save it with German strings.

I got it.

**Pull request closed without merging**
